<?php
/*
Problem: Even Fibonacci numbers

Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

https://github.com/AbdullahAlfaraj/project-euler/
by Abdullah Alfaraj
*/

function nextFibo($f1, $f2) {
    return $f1 + $f2;
}

function sumEvenTerms($f1, $f2, $sum, $condition) {
    //even and less than condition
    if (($f1 % 2 == 0) && ($f1 <= $condition))
        $sum += $f1;

    if (($f2 % 2 == 0) && ($f2 <= $condition))
        $sum += $f2;
    if($f1 > $condition && $f2 > $condition)
        return $sum;
    else
    {
        $f3 = nextFibo($f1,$f2);
        $f4 = nextFibo($f2,$f3);
        return sumEvenTerms ($f3, $f4, $sum, $condition);
}
}

$f1 = 1;
$f2 = 2;
$sum = 0;
$condition = 4 * 1000000;
echo "sum: ".sumEvenTerms($f1, $f2, $sum, $condition) ."\n";